[package]
name = "patoz"
version = "0.1.0"
authors = ["orhanbalci@gmail.com <orhanbalci@gmail.com>"]
edition = "2018"

[dependencies]
nom = "5.0.1"
chrono = "0.4"
itertools = "0.8"

[dev-dependencies]
serde_json="1.0"
